### PR TITLE
feat: adding pt-br translations

### PR DESCRIPTION
**Pull request by vbpns**
This PR will add PT-BR translations

### CODE REVIEW

**Comment by prokopsimek** [comment]
@guidroid @vbpns Hi, thank you so much for your PR! 🤩 May I ask you, have you done at least a 4-eye review of the translation? As I don't understand it I am not able to check the correctnes.

**Comment by prokopsimek** [comment]
@vbpns Please, remove the `static_locales_pt-br_common.json` file in the PR. I have tried to do it but I don't have permission to update it in your repository. I have moved this translation to our private app repository.

And also rename change letter case in file names from `pt-br` to `pt-BR` to fulfill the ISO standard. The app ([next-i18next](https://github.com/isaachinman/next-i18next)) needs it to correctly load these translations.

@guidroid @vbpns If you send me your LinkedIn profiles, I will add you to the collective of authors in pt-BR translation. 👍 

Thank you! 🙂

**Comment by guiofsaints** [comment]
This translations has been reviewed by:

@AndersonSalcedoBR 
https://www.linkedin.com/mwlite/in/anderson-salcedo-49328416a

@vbpns 
https://www.linkedin.com/mwlite/in/viniciusblasek

@ImRamos97
https://www.linkedin.com/mwlite/in/igor-ramos-127737140

@guidroid
https://www.linkedin.com/mwlite/in/guilherme-dos-santos

**Comment by prokopsimek** [comment]
Thanks a lot! 👏 🎉

**Comment by prokopsimek** [comment]
It's up! https://developerexperiencemanifesto.org/pt-BR/

**Pull request merged**
